GET http://localhost:4000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSm9obiIsImlhdCI6MTY5MDQ5MjE1MX0.YiKGoi0_L4xYTTTjxgpzev787i3JqMbSrvbmk2kgoAw


###

POST http://localhost:4000/login
Content-Type: application/json

{
  "username": "Ruaraidh",
  "password": "password"
}
